<?php
// $Id$

function extlink_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    $items[] = array(
      'path' => 'admin/settings/extlink',
      'title' => t('External links'),
      'description' => t('Alter the display of external links on the site.'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('extlink_admin_settings'),
      'access' => user_access('administer site configuration')
    );
  }
  else {
    $path = drupal_get_path('module', 'extlink');
    drupal_add_js($path. '/extlink.js');
    drupal_add_js(array('extlink' => array('extTarget' => variable_get('extlink_target', 0), 'extClass' => variable_get('extlink_class', 'ext'), 'baseUri' => 'http://' . $_SERVER['HTTP_HOST'])), 'setting');
    if (variable_get('extlink_class', 'ext')) {
      drupal_add_css($path. '/extlink.css');
    }
  }
  return $items;
}

function extlink_admin_settings () {
  $form = array();

  $form['extlink_class'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add icon to external links'),
    '#return_value' => 'ext',
    '#default_value' => variable_get('extlink_class', 'ext'),
    '#description' => t('Places an !icon icon next to external links.', array('!icon' => theme_image(drupal_get_path('module', 'extlink') . '/extlink.png'))),
  );

  $form['extlink_target'] = array(
    '#type' => 'checkbox',
    '#title' => t('Open external links in a new window'),
    '#return_value' => '_blank',
    '#default_value' => variable_get('extlink_target', 0),
    '#description' => t('Should all external links be opened in a new window?'),
  );
  
  return system_settings_form($form);
}