<?php

function extlink_menu() {
  $items = array();
  $items['admin/config/user-interface/extlink'] = array(
    'title' => 'External links',
    'description' => 'Alter the display of external links on the site.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('extlink_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Implementation of hook_init().
 */
function extlink_init() {
  $path = drupal_get_path('module', 'extlink');
  drupal_add_js($path .'/extlink.js', array('every_page' => TRUE));
  $settings = array(
    'extTarget'     => variable_get('extlink_target', 0),
    'extClass'      => variable_get('extlink_class', 'ext'),
    'extSubdomains' => variable_get('extlink_subdomains', 1),
    'extExclude'    => variable_get('extlink_exclude', ''),
    'extInclude'    => variable_get('extlink_include', ''),
    'extAlert'      => variable_get('extlink_alert', 0),
    'mailtoClass'   => variable_get('extlink_mailto_class', 'mailto')
  );
  if (variable_get('extlink_alert' == '1')) {
    $settings['extAlertText']  = variable_get('extlink_alert_text', 'This link will take you to an external web site. We are not responsible for their content.');
  } else if (variable_get('extlink_alert') == 2) {
    $settings['extAlertText'] = variable_get('extlink_alert_overlay_text', 'Goodbye!');
  }
  drupal_add_js(array('extlink' => $settings),'setting');
  if (variable_get('extlink_class', 'ext') == 'ext' || variable_get('extlink_mailto_class', 'mailto') == 'mailto') {
    drupal_add_css($path . '/extlink.css', array('every_page' => TRUE));
  }
}

function extlink_admin_settings() {
  $form = array();

  $form['extlink_class'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add icon to external links'),
    '#return_value' => 'ext',
    '#default_value' => variable_get('extlink_class', 'ext'),
    '#description' => t('Places an !icon icon next to external links.', array('!icon' => theme('image', array('path' => drupal_get_path('module', 'extlink') . '/extlink.png', 'alt' => t('External Links icon'))))),
  );

  $form['extlink_mailto_class'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add icon to mailto links'),
    '#return_value' => 'mailto',
    '#default_value' => variable_get('extlink_mailto_class', 'mailto'),
    '#description' => t('Places an !icon icon next to mailto links.', array('!icon' => theme('image',array('path' => drupal_get_path('module', 'extlink') . '/mailto.png', 'alt' => t('Email links icon'))))),
  );

  $form['extlink_subdomains'] = array(
    '#type' => 'checkbox',
    '#title' => t('Consider subdomains internal'),
    '#default_value' => variable_get('extlink_subdomains', 1),
    '#description' => t('If checked, links with the same primary domain will all be considered internal. A link from www.example.com to my.example.com would be considered internal. Links between the www. and non-www. domain are always considered internal.'),
  );

  $form['extlink_target'] = array(
    '#type' => 'checkbox',
    '#title' => t('Open external links in a new window'),
    '#return_value' => '_blank',
    '#default_value' => variable_get('extlink_target', 0),
    '#description' => t('Should all external links be opened in a new window?'),
  );

  $form['warnings'] = array(
    '#tree' => FALSE,
    '#type' => 'fieldset',
    '#title' => t('Leave warning'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => 'Display a warning to users before leaving the site' 
  );

  $form['warnings']['extlink_alert'] = array(
    '#type' => 'select',
    '#title' => t('External link warning type'),
    '#options' => array(
        '0' => t('None'),
        '1' => t('Simple alert displayed'),
        '2' => t('Overlay'),
      ),
    '#default_value' => variable_get('extlink_alert', 0),
    '#description' => t('Choose action when an external link is clicked.'),
  );

  $form['warnings']['extlink_alert_text'] = array(
    '#type' => 'textarea',
    '#rows' => 3,
    '#title' => t('Pop-up warning text'),
    '#default_value' => variable_get('extlink_alert_text', 'This link will take you to an external web site. We are not responsible for their content.'),
    '#description' => t('Text to display in the pop-up external link warning box.'),
    '#wysiwyg' => FALSE,
    '#states' => array(
      'visible' => array(
          'select[name="extlink_alert"]' => array('value' => '1'),
        ),
      ),
  );

  $form['warnings']['extlink_alert_overlay_wait'] = array(
    '#type' => 'select',
    '#title' => t('time to display overlay (seconds)'),
    '#options' => drupal_map_assoc(array('1','2','3','4','5','6','7','8','9','10')),
    '#default_value' => variable_get('extlink_alert_overlay_wait',3),
    '#states' => array(
      'visible' => array(
          'select[name="extlink_alert"]' => array('value' => '2'),
        ),
      ),
  );

  $form['warnings']['extlink_alert_overlay_text'] = array(
    '#type' => 'textarea',
    '#title' => t('Overlay warning text'),
    '#description' => t('Text to display in overlay.  [URL] will be replaced with the link target'),
    '#default_value' => variable_get('extlink_alert_overlay_text',t('Thank you for visiting this site.  You are about to be redirected to: <p>[URL]</p>')),
    '#states' => array(
      'visible' => array(
          'select[name="extlink_alert"]' => array('value' => '2'),
        ),
      ),
  );

  $form['warnings']['extlink_alert_patterns'] = array(
    '#type' => 'textfield',
    '#title' => t('Ignore links matching the pattern'),
    '#maxlength' => NULL,
    '#default_value' => variable_get('extlink_alert_patterns', ''),
    '#description' => t('Enter a regular expression for links that you wish to exclude from receiving an alert.  See the patterns section below for details.
            The link will still received the other external treatments.'),
  );

  $patterns = array(
    '<em>(example\.com)</em> ' . t('Matches example.com.'),
    '<em>(example\.com)|(example\.net)</em> ' . t('Multiple patterns can be strung together by using a pipe. Matches example.com OR example.net.'),
    '<em>(links/goto/[0-9]+/[0-9]+)</em> ' . t('Matches links that go through the <a href="http://drupal.org/project/links">Links module</a> redirect.'),
  );

  $wildcards = array(
    '<em>.</em> ' . t('Matches any character.'),
    '<em>?</em> ' . t('The previous character or set is optional.'),
    '<em>\d</em> ' . t('Matches any digit (0-9).'),
    '<em>[a-z]</em> ' . t('Brackets may be used to match a custom set of characters. This matches any alphabetic letter.'),
  );

  $form['patterns'] = array(
    '#tree' => FALSE,
    '#type' => 'fieldset',
    '#title' => t('Pattern matching'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' =>
      '<p>' . t('External links uses patterns (regular expressions) to match the "href" property of links.') . '</p>' .
      t('Here are some common patterns.') .
      theme('item_list', array("items" => $patterns)) .
      t('Common special characters:') .
      theme('item_list', array("items" => $wildcards)) .
      '<p>' . t('All special characters (<em>^ $ . ? ( ) | * +</em>) must also be escaped with backslashes. Patterns are not case-sensitive. Any <a href="http://www.javascriptkit.com/javatutors/redev2.shtml">pattern supported by JavaScript</a> may be used.') . '</p>',
  );

  $form['patterns']['extlink_exclude'] = array(
    '#type' => 'textfield',
    '#title' => t('Exclude links matching the pattern'),
    '#maxlength' => NULL,
    '#default_value' => variable_get('extlink_exclude', ''),
    '#description' => t('Enter a regular expression for links that you wish to exclude from being considered external.'),
  );

  $form['patterns']['extlink_include'] = array(
    '#type' => 'textfield',
    '#title' => t('Include links matching the pattern'),
    '#maxlength' => NULL,
    '#default_value' => variable_get('extlink_include', ''),
    '#description' => t('Enter a regular expression for internal links that you wish to be considered external.'),
  );

  return system_settings_form($form);
}
